language: python
install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - coverage run --source='.' manage.py test
  - python manage.py check
  - python manage.py migrate

after_success:
  - coveralls