language: python
before-install:
  - pip install -r requirements.txt
  - pip install black
  - pip install coverage
  - pip install coveralls

script:
  - black --check .
  - coverage run --source='.' manage.py test
  - python manage.py check
  - python manage.py migrate

after_success:
  - coveralls